#MAIN ENTITIES
USERS: {
  shape: sql_table

  # FIELDS
  user_id: int {constraint: primary_key}
  name_id: int {constraint: foreign_key}
  surname_id: {constraint: foreign_key}
  email_id: {constraint: foreign_key}
  phone_number_id: {constraint: foreign_key}
  avatar_id: {constraint: foreign_key}
  # ...
}

CHATS: {
  shape: sql_table

  # FIELDS
  chat_id: int {constraint: primary_key}
  isavailable: bool
  number_of_people: int
  number_of_messages: int
  # ...
}

# Merged table of user-chat -- many-to-many
CHAT_PARTICIPANTS: {
  shape: sql_table

  # FIELDS
  participant_id: int {constraint: primary_key}
  user_id: int {constraint: foreign_key}
  chat_id: int {constraint: foreign_key}
  # ...
}

CHAT_PARTICIPANTS_ROLE: {
  shape: sql_table

  role_id: int {constraint: primary_key}
  participant_id: int {constraint: foreign_key}
  role: string
}

MESSAGES: {
  #Represents a message entity
  shape: sql_table
  
  #FIELDS
  message_id: int {constraint: primary_key}
  user_id: int {constraint: foreign_key}
  chat_id: int{constraint: foreign_key}
  message_text: string
  time_stamp: datetime
}


ORGANIZATIONS: {
  shape: sql_table

  #FIELDS
  organization_id: int {constraint: primary_key}
  name: string
}

ORGANIZATIONS_STAFF:{
  shape: sql_table

  #FIELDS
  staff_id: int {constraint: primary_key}
  organization_id: int {constraint: foreign_key}
  user_id(O): int? {constraint: foreign_key} #a personel can be in an organization, but not registred as a user
  role_id: int {constraint: foreign_key}  
  name: string
  lastname: string
  position: string  
}

ORGANIZATIONS_ROLES:{
  shape: sql_table

  #FIELDS
  role_id: int {constraint: primary_key}
  role: string  
}


# RELATIONSHIPS
USERS <->  USERS_ATTRIBUTES:{
  source-arrowhead: 1 {
    shape: cf-one-required
    style.filled: true
  } 
  target-arrowhead: 1 {
    shape: cf-one-required
    style.filled: true
  } 
}


 
USERS -> CHAT_PARTICIPANTS:{
  style: {
    stroke-dash: 3   
  }
  source-arrowhead: 1
  target-arrowhead: 0..* {
    shape: cf-many
    style.filled: true    
  } 
}

CHATS ->CHAT_PARTICIPANTS:{
  style: {
    stroke-dash: 3   
  }
  source-arrowhead: 1
  target-arrowhead: 0..* {
    shape: cf-many
    style.filled: true
  } 
}


CHAT_PARTICIPANTS -> CHAT_PARTICIPANTS_ROLE:{
  source-arrowhead: 1
  target-arrowhead: 0..* {
    shape: cf-many
    style.filled: true
  } 
}


USERS -> MESSAGES:{
  source-arrowhead: 1
  target-arrowhead: 0..* {
    shape: cf-many
    style.filled: true
  } 
}

 
 

CHATS -> MESSAGES:{
  source-arrowhead: 1
  target-arrowhead: 0..* {
    shape: cf-many
    style.filled: true
  } 
}


ORGANIZATIONS <-> ORGANIZATIONS_STAFF:{
  source-arrowhead: {
    shape: cf-one-required
    style.filled: true 
  }
  target-arrowhead: 1..* {
    shape: cf-many
    style.filled: true
  } 
}

ORGANIZATIONS_STAFF <-> USERS:{
  #staff member has 0 or 1 account, therefore it is zero or one relationship
  source-arrowhead: 1 {
    shape: cf-one-required
    style.filled: true
  } 
  target-arrowhead: 0..1 {
    shape: cf-one-required
    style.filled: true
  } 
}


ORGANIZATIONS_STAFF <-> ORGANIZATIONS_ROLES:{
   #staff member has one organization role 
   source-arrowhead: 1 {
    shape: cf-one-required
    style.filled: true
  } 

   target-arrowhead: 1 {
    shape: cf-one-required
    style.filled: true
   } 

}


# ISOLATED TABLES
USERS_ATTRIBUTES: { 
  #Kepps users attributes like name, surname, phone, avatar etc.
  
  shape: stored_data


  NAMES: { 
    #keeps the table of various names
    shape: sql_table

    name_id: int {constraint: primary_key}
    name: string {constraint: unique}
  }

  SURNAMES: {
    #keeps the table of various surnames
    shape: sql_table

    surname_id: int {constraint: primary_key}
    surname: string {constraint: unique}
  }

  PHONES:{
    #keeps the table of unique phones
    shape: sql_table

    phone_id: int {constraint: primary_key}
    phone_number: string {constraint: unique}
  }

  EMAILS:{
    #keeps the table of avatars
    shape: sql_table

    email_id: int {constraint: primary_key}
    email: string {constraint: unique}
  }

  AVATARS:{
    #keeps the table of avatars
    shape: sql_table

    avatar_id: int {constraint: primary_key}
    url: string {constraint: unique}
  }

}